// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtxZEIStM5k-E-Uy2qLjjGUHqDzHQfv-Q',
    appId: '1:729652281854:web:343fa8ddf2dd2c626d00af',
    messagingSenderId: '729652281854',
    projectId: 'book-app-87882',
    authDomain: 'book-app-87882.firebaseapp.com',
    storageBucket: 'book-app-87882.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5LyWt7QsWGY2aSKEIfgW48B5k_kM0p0',
    appId: '1:729652281854:ios:a047595996cab8a06d00af',
    messagingSenderId: '729652281854',
    projectId: 'book-app-87882',
    storageBucket: 'book-app-87882.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtxZEIStM5k-E-Uy2qLjjGUHqDzHQfv-Q',
    appId: '1:729652281854:web:aa0fedfb811b49a06d00af',
    messagingSenderId: '729652281854',
    projectId: 'book-app-87882',
    authDomain: 'book-app-87882.firebaseapp.com',
    storageBucket: 'book-app-87882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5LyWt7QsWGY2aSKEIfgW48B5k_kM0p0',
    appId: '1:729652281854:ios:a047595996cab8a06d00af',
    messagingSenderId: '729652281854',
    projectId: 'book-app-87882',
    storageBucket: 'book-app-87882.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPVAV37cSe9Das9HoOFWBo0qAPDOYmJA',
    appId: '1:729652281854:android:aa7a4c18c3f1ca8b6d00af',
    messagingSenderId: '729652281854',
    projectId: 'book-app-87882',
    storageBucket: 'book-app-87882.firebasestorage.app',
  );

}